### ISSUE TITLE
Support Datetime types for date params

### ISSUE THREAD

**Issue by calve** [vehemont/nvdlib#1]
Hi, great lib thanks !

as of today,  all the `Date` parameters accepts date-formated string only. What do you think about accepting datetime ? 

That is, today, I have to write

```python
end = datetime.datetime.now()
start = end - datetime.timedelta(days=7)
self.cves = nvdlib.searchCVE(
            pubStartDate=start.strftime("%Y-%m-%d %H:%M"),
            pubEndDate=end.strftime("%Y-%m-%d %H:%M")
)
```

but we could have this interface

```python
end = datetime.datetime.now()
start = end - datetime.timedelta(days=7)
self.cves = nvdlib.searchCVE(
            pubStartDate=start,
            pubEndDate=end
)
```

I can implemented this if your OK and found a few free hours.

**Comment by vehemont** [comment]
Hello. Thank you for the suggestion, I like the idea of passing a datetime object as well.

Here is the date parsing right now that requires a string:
```python
        if pubStartDate:
            date = str(datetime.strptime(pubStartDate, '%Y-%m-%d %H:%M').isoformat()) + ':000 UTC-00:00'
            pubStartDate = 'pubStartDate=' + date
            parameters.append(pubStartDate)
```

Passing a datetime object instead would allow the user more flexibility. This can be accomplished by accepting a datetime object, converting to ISO 8601, setting microseconds to 0, then adding the UTC offset. This will be updated for the modified date searchCVE argument as well.

```python
        if pubStartDate:
            date = pubStartDate.replace(microsecond = 0).isoformat() + ':000 UTC-00:00'
            pubStartDate = 'pubStartDate=' + date
            parameters.append(pubStartDate)
```

Example:

```python
>>> import nvdlib
>>> import datetime
>>> end = datetime.datetime.now()
>>> start = end - datetime.timedelta(days=7)
>>> r = nvdlib.searchCVE(pubStartDate=start, pubEndDate=end, verbose=True)
Filter:
https://services.nvd.nist.gov/rest/json/cves/1.0?pubStartDate=2022-02-08T08:57:26:000 UTC-00:00&pubEndDate=2022-02-15T08:57:26:000 UTC-00:00
>>> len(r)
629
```

Do you agree with this implementation? Please let me know if you think anything is missing.

**Comment by calve** [comment]
Thanks for your interrest. Few things that come to my mind;

 - you probably still want to accept `pubStartDate` as string to avoid breaking existant implemantations. You can achieve this with python `type()` or `instanceof()` functions
 - or if you're willing to break compatibility, we could also return Datetime objects for cve dates instead of strings. Not sure of the implications here
 - Looks like the `:000 UTC-00:00` string cannot be pulled from the Datetime module instead of being appended as a string :/ (https://docs.python.org/3/library/datetime.html) Also we are in timezone territory here and should be carefull. The nvd api appears to be strict and returns a message `Date format should be yyyy-MM-dd'T'HH:mm:ss:SSS z`
   - more of an implementation details but it seems you build the final query string via multiple `parameters.append(pubStartDate)`, which seems to be then passed as a string to `request.get()`. You can leverage to do the hardwork for you and just call `request.get('somewhere.at.nvid/', params={'key': 'value'}` (https://docs.python-requests.org/en/latest/user/quickstart/?highlight=passing-parameters-in-urls). This is probably a bigger rework.

all in all, I'd implement something allong the lines of

```python
import datetime
def searchCve(pubEndDate=False, pubStartDate=False):
   parameters = {}
   if pubStartDate:
      try:
        parameters['pubStartDate'] =   pubStartDate.replace(microsecond = 0).isoformat() + ':000 UTC-00:00'
      except AttributeError:
         # well, hope pubStartDate is already a string then
         parameters['pubStartDate'] = pubStartDate
    # repeat for all dates
    # also adapt all others parameters, beware of booleans & edge cases

# latter in __get()
def __get(product, parameters, limit, key, verbose):
    # let request handle the query string or us
    # also remove the trailing ? from link
    raw = request.get(link, data=parameters)
```

Anyway, on the overall interface and implementation your suggestion looks good to me ! Let me know if you need me to provide pull requests or test your patches.

**Comment by vehemont** [comment]
You have been super helpful. I really appreciate the time you've put into showing me these enhancements. I was not aware of the ability to pass parameters as a dictionary in this use case. I have always felt the current method I have of building the request using strings was clunky. I've went ahead and reworked this into NVDLib. It now will utilize the params argument in a GET request through requests.

I've also implemented passing a datetime object to searchCVE and searchCPE with `isinstance(pubStartDate, datetime)` to check if the passed parameter is a datetime object or string to allow backwards compatibility.

As for returning datetime objects in CVEs, are you referring to the `publishedDate` and `lastModifiedDate` values that are located in a response from retrieving a CVE collection or single CVE? I can get get those converted to datetime objects as well. I will give each CVE object a new attribute called `publishedDate` and `lastModifiedDate` that is converted to a datetime object for easy access.

**Comment by calve** [comment]
> As for returning datetime objects in CVEs, are you referring to the publishedDate and lastModifiedDate values that are located in a response from retrieving a CVE collection or single CVE? I can get get those converted to datetime objects as well. I will give each CVE object a new attribute called publishedDate and lastModifiedDate that is converted to a datetime object for easy access.

Yes ! 

Once again beware of breaking changes :) I think adding a new attribute wont break existing usage but I understand there is already a `self.cve.lastModifiedDate` attribute as a string. Are you referring to adding `self.lastModifiedDate` ?
Alternatively it could be named `lastModifiedDatetime` but it wont keep a 1-1 mapping with the nvdlib API so the choice is your I guess

**Comment by calve** [comment]
Just to let you know that version 0.5.6, implementing #1 looks good to me !
Many thanks. Feel free to close this issue.

**Comment by vehemont** [comment]
I will get this issue closed for now. Please feel free to open more if you find any bugs or have any feature requests. 

I will work on getting datetime objects into a new attribute named `lastModifiedDatetime`. My intention is to leave the API response for a CVE intact while providing additional attributes for the most accessed information, similar to the score attribute.
