### ISSUE TITLE
ExactMatch parameter is not working

### ISSUE THREAD

**Issue by Padmanaabhah** [vehemont/nvdlib#12]
The records which i get from NVDLib library and nvd.nist.gov are not matching. using the below query with the parameters
r = nvdlib.searchCVE(pubStartDate='2022-06-18 00:00', pubEndDate = '2022-10-16 00:00', keyword = 'Entity Framework', exactMatch=True, verbose=True)    

With NVDlib It returns 3 records. when i do the same search in nvd.nist.gov i get 0 records. i feel the nvdlib library has an issue in applying the filter 'Exact match'. As you see below one of the result returned doesnt contain the term 'Entity framework' but still shown in the result.

![image](https://user-images.githubusercontent.com/23008726/196411197-cf7cac16-11cd-4d8b-9467-e255d6a4b85c.png)

can anyone point me why exactmatch is not considered or am i missing something

**Comment by vehemont** [comment]
Hello,

You are correct the `exactMatch` parameter is no longer working. It seems the parameter changed at some point and is now `isExactMatch`

I've updated `cve.py` to reflect this change and it will now correctly utilize the parameter. I've pushed this update out as NVDLib 0.6.1. I've tested the search query you provided and it returned the expected 0 results, but please let me know if the changes work as expected for you.

**Comment by Padmanaabhah** [comment]
Thanks for the quick fix. It helped
