### ISSUE TITLE
Can't search for CVE by CVSSv3 severity

### ISSUE THREAD

**Issue by JJP0** [vehemont/nvdlib#13]
I am trying to search for all critical/high/medium/low vulnerabilities that were released within the last month, using the below line for criticals:
`crit_monthly_cves = nvdlib.searchCVE(pubStartDate=prev_month_first, pubEndDate=prev_month, cvssV3Severity='Critical')`

This line works as soon as I take out the 'cvssV3Severity' parameter, however it throws this error when trying it with the parameter:

`Invalid search criteria syntax: <Response [403]>
Attempted search criteria: {'pubStartDate': '2022-09-01T00:00:42:000 UTC-00:00', 'pubEndDate': '2022-09-30T00:00:42:000 UTC-00:00', 'cvssV3Severity': 'CRITICAL'}`

```
File "C:\Users\xxx\PycharmProjects\xxx\venv\lib\site-packages\nvdlib\cve.py", line 308, in searchCVE
    raw = __get('cve', parameters, limit, key, verbose)
  File "C:\Users\xxx\PycharmProjects\xxx\venv\lib\site-packages\nvdlib\get.py", line 41, in __get
    totalResults = raw['totalResults']
TypeError: 'Response' object is not subscriptable
```

**Comment by vehemont** [comment]
Hello,

What version of NVDLib are you using? I was not able to replicate the issue on NVDLib version 0.6.1.  I am going to be releasing NVDLib 0.7.0 very soon, and I wasn't able to replicate the issue on that version either. 


My test on 0.6.1:
```
>>> import nvdlib
>>> prev_month_first='2022-09-01 00:00'
>>> prev_month='2022-09-30 00:00'
>>> crit_monthly_cves = nvdlib.searchCVE(pubStartDate=prev_month_first, pubEndDate=prev_month, cvssV3Severity='Critical', verbose=True)
Filter:
https://services.nvd.nist.gov/rest/json/cves/2.0?cvssV3Severity=CRITICAL&pubStartDate=2022-09-01T00:00:00&pubEndDate=2022-09-30T00:00:00
>>> len(crit_monthly_cves)
331
```

**Comment by JJP0** [comment]
Ah, that is my mistake.

I was using version 0.6.0 - I have just upgraded to 0.6.1 and it shows the same results that you found. 

Thank you!
