### ISSUE TITLE
Change in the JSON result of nvdlib.searchCVE (cvssMetricsV2)

### ISSUE THREAD

**Issue by Gerox7** [vehemont/nvdlib#16]
Hi,

For an unknown reason, between Thursday December 15, 2022 and Monday December 19, 2022, NVD must have changed its JSON generation and this impacts NVDLib. For example the searchCVE function that returns an error :
![ResultNVDLIB](https://user-images.githubusercontent.com/108056826/208411418-d5af4b8b-1cd7-4d83-a531-11041431e2f2.png)
Here is the JSON response to my request:
![JSONNVD](https://user-images.githubusercontent.com/108056826/208411537-f752bf67-2044-434e-8fe9-03d820b270b2.png)
We can see that "metrics.cvssMetricV2[0].cvssData.baseSeverity" doesn't exist anymore but we find it here: "metrics.cvssMetricV2[0].baseSeverity".
To correct this I changed line 181 of the file "[...]/nvdlib/classes.py" : 
![CorrectNVDLIB](https://user-images.githubusercontent.com/108056826/208412050-543cd36e-ba84-458c-bac0-7ff7e41789c2.png)

I don't know if it's a permanent change but changing this line solved the problem

**Comment by vehemont** [comment]
Hi 

Thank you for pointing this out. I am working on a fix right now and will push it out ASAP.

**Comment by vehemont** [comment]
I've updated NVDLib to 0.7.1 to resolve this issue. Please test out the new version and let me know if it works for you.

**Comment by vehemont** [comment]
I sent an email to the NVD API team to see if this is an unintended or intended change. The [documentation](https://nvd.nist.gov/developers/vulnerabilities) under the `metrics` response does not reflect this change at the moment. 

![image](https://user-images.githubusercontent.com/48965163/208476555-92cec6e2-6a1b-4fc0-af8c-4dbc18f821ec.png)

**Comment by vehemont** [comment]
The NVD team has responded to me and clarified having CVSS version 2 `baseSeverity` outside of `cvssData` is an intended change and they will update the documentation to reflect the change.

**Comment by Gerox7** [comment]
Thanks @vehemont for the quick answer and correction
