### ISSUE TITLE
Adding CVE Change API

### ISSUE THREAD

**Issue by simonkleinfeld** [vehemont/nvdlib#17]
Hi,

Do you plan to integrate the CVE Changelog API into the library in the future?
It's described here: https://nvd.nist.gov/developers/vulnerabilities

**Comment by vehemont** [comment]
Hi,

Yes. There are plans to include the other missing API endpoints such as the Change History API, Source API, and Match Criteria API. I do not have an ETA on when they will be released, but they are being worked on.

#15

**Comment by simonkleinfeld** [comment]
Perfect thanks! Makes my analysis for my master thesis easier.
