### ISSUE TITLE
Make API support more complete

### ISSUE THREAD

**Issue by firmianay** [vehemont/nvdlib#18]
nvdlib's support for API 2.0 does not seem to be comprehensive. For example, I hope to use the "startIndex" and "resultsPerPage" parameters to gradually build a local repository. https://nvd.nist.gov/developers/api-workflows
Of course, there are other parameters that I have not tested.

**Comment by vehemont** [comment]
Hi,

Those parameters were purposely not included to be passed within a search or query using NVDLib as they are used automatically within the library to page through all results. NVDLib's purpose is to provide a simple way to access the NVD API when you have minimum information and you don't want to deal with any of the technical aspects of paging, rate limiting, or sending POST requests.

If you would prefer to use the `startIndex` or `resultsPerPage` parameters yourself, you are better off accessing the API directly not through NVDLib. The NVD API can be accessed directly with ease using a library like [Requests](https://github.com/psf/requests). NVDLib uses the Requests library on the backend to do most of the heavy lifting already. To get a good idea of how to access the API directly, I recommend taking a look inside NVDLib's [get.py](https://github.com/vehemont/nvdlib/blob/main/nvdlib/get.py). I used the `startIndex` and `resultsPerPage` parameters here, and the code can be easily modified to fit any needs and pass any parameters. 

I hope this helps.
