### ISSUE TITLE
Error when searching CVEs by CPE name

### ISSUE THREAD

**Issue by robthew** [vehemont/nvdlib#21]
I got an an HTTP 404 error when searching for CVEs using the CPE name returned from a CPE search. It appears that CPE names may contain special characters that if not escaped, will cause the NVD API to return a 404.

```
>>> import nvdlib
>>> terms='wptaskforce'
>>> cpes = nvdlib.searchCPE(keywordSearch=terms, key=key, limit=1)
>>> for eachCPE in cpes:
...     print(eachCPE.cpeName)
... 
cpe:2.3:a:wptaskforce:track_\&_trace:6.9.5:*:*:*:*:wordpress:*:*
>>> for eachCPE in cpes:
...     cves = nvdlib.searchCVE(cpeName=eachCPE.cpeName, key=key)
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/Users/rthew/Library/Python/3.9/lib/python/site-packages/nvdlib/cve.py", line 270, in searchCVE
    raw = __get('cve', headers, parameters, limit, verbose, delay)
  File "/Users/rthew/Library/Python/3.9/lib/python/site-packages/nvdlib/get.py", line 24, in __get
    raw.raise_for_status()
  File "/Users/rthew/Library/Python/3.9/lib/python/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error:  for url: https://services.nvd.nist.gov/rest/json/cves/2.0?cpeName=cpe:2.3:a:wptaskforce:track_%5C&_trace:6.9.5:*:*:*:*:wordpress:*:*
```

I can get around this by escaping each `cpeName` using the `urllib` library, but it would be nice if the searchCVE function handled this itself.

Thanks!

**Comment by vehemont** [comment]
Hi,

Thanks for submitting this issue. I am able to replicate this issue. Would you be able to share your method of escaping the `cpeName` with `urllib`? Are you using `urllib.parse`?

**Comment by robthew** [comment]
Yes, I'm using `urllib.parse.quote_plus` like you have there

**Comment by vehemont** [comment]
I have updated NVDLib to 0.7.2 to resolve this issue. Please give it a try and let me know if it works as you expect.

Thanks again for submitting this issue.
