### ISSUE TITLE
Supporting new CVSS v4.0

### ISSUE THREAD

**Issue by akuster** [vehemont/nvdlib#33]
NVD released version 4.0 on Nov 1st.

https://www.first.org/cvss/v4-0/
https://www.first.org/cvss/v4.0/specification-document
https://www.first.org/cvss/cvss-v4.0.json

Are there plans in motion to add v4.0 support?

**Comment by vehemont** [comment]
Hi,

CVSS 4.0 is not available in the [NVD API](https://nvd.nist.gov/developers/vulnerabilities), yet. I do my best to keep the vulnerabilities and products API parameters up to date. If CVSS 4.0 gets released on the API, I will gladly add support for it. NVD sometimes updates parameters without sending out an update to the API mailing list, so if CVSS 4.0 shows up in the API and NVDLib is not updated, please open another issue.
