### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by Fares-Abubaker** [vehemont/nvdlib#37]
i get this error always 

```
HTTPSConnectionPool(host='services.nvd.nist.gov', port=443): Read timed out. (read timeout=30)
```

**Comment by vehemont** [comment]
Hi,

This error usually means that your system you are running NVDLib on is failing a connection to the NVD API, and not a problem with the NVDLib library itself. I suggest ensuring your internet connection doesn't disconnect, or troubleshooting why your computer is failing to establish a connection the NVD API at "services.nvd.nist.gov".

Thank you,
vehemont

**Comment by Fares-Abubaker** [comment]
My internet connection is good, but the NVD service has a problem

**Comment by vehemont** [comment]
I was able to replicate this issue using the following command: `r = nvdlib.searchCVE(keywordSearch='Microsoft')`. I do believe there is an issue with the NVD API as you have stated. I see requests taking upwards of over 60 seconds but on average 45 seconds, which is above the threshold for NVDLibs 30 second timeout. I have reached out to the NVD team with this finding and will reply to this issue once I receive a response.

**Comment by ammerzon** [comment]
I get the same error on my side including `503 Server Error: Service Unavailable for url`. Thank you @vehemont for reaching out to the NVD team.

**Comment by vehemont** [comment]
I received an update that the NVD API is having issues at this time and the team is aware. I'll keep this issue open to post further updates and for visibility.

> Thank you for notifying the NVD. We are aware of timeout errors being provided to users of the vulnerability search page and APIs and are currently investigating the root cause for resolution. We apologize for the inconvenience during this time.

**Comment by Fares-Abubaker** [comment]
@vehemont Thanks for your update

**Comment by D0wn10ad** [comment]
Hi,

Please also consider https://github.com/vehemont/nvdlib/pull/38

Regards,
Titus

**Comment by D0wn10ad** [comment]
occasionally (Asia region)

**Comment by vehemont** [comment]
I got an update from the NVD that they are still trying to resolve the 503 errors:

> Thank you for the feedback email. We are aware of the current performance issues with the API (specifically the 503 errors) and are actively working to address them.  We apologize for the inconvenience.

**Comment by Fares-Abubaker** [comment]
The issue still for now

**Comment by vehemont** [comment]
I am no longer receiving timeout or 503 errors. Can someone else confirm before I close this issue?

**Comment by johnlabuyfoy1024** [comment]
I can confirm that.

Thank you for creating and maintaining nvdlib!

**Comment by Fares-Abubaker** [comment]
I still get this error everyday:

```
403 Client Error: Forbidden for url: https://services.nvd.nist.gov/rest/json/cves/2.0?keywordSearch=pandas&virtualMatchString=cpe%3A2.3%3Aa%3A%2A!
```

**Comment by Fares-Abubaker** [comment]
@vehemont The issue still occurs for me ,, you don't get the same?

**Comment by vehemont** [comment]
> @vehemont The issue still occurs for me ,, you don't get the same?

I do not receive any 403 error. This usually means you are hitting the rate limit in some way. You could try setting the delay parameter to something like 12 seconds, instead of the default 6 seconds. Using the same API key on multiple instances can induce the rate limit error since they are tracked with the same rate limit. This is also true if you are accessing the NVD API with multiple instances from a single IP address with no API key.

**Comment by Fares-Abubaker** [comment]
@vehemont You are right, I fixed it, thanks
