### ISSUE TITLE
Add support for cpematch API endpoint

### ISSUE THREAD

**Issue by zimage** [vehemont/nvdlib#40]
There is another CPE endpoint for doing server-side CPE string matching. The documentation is here under the section titled "Match Criteria API". Could you add support for this?

https://nvd.nist.gov/developers/products

**Comment by firmianay** [comment]
Is there any update on the progress? This API is important to me because I only need to specify the vendor and product, not the specific version number.
```
https://services.nvd.nist.gov/rest/json/cpes/2.0?cpeMatchString=cpe:2.3:o:microsoft:windows_10
https://services.nvd.nist.gov/rest/json/cves/2.0?cpeName=cpe:2.3:o:microsoft:windows_10:1607
```

**Comment by vehemont** [comment]
This API has been added in the recent release.  
  
https://github.com/vehemont/nvdlib/releases/tag/v0.7.7
