### ISSUE TITLE
Invalid search Errors

### ISSUE THREAD

**Issue by ithrasiel** [vehemont/nvdlib#6]
Hi,

i'm using the nvdlib to search CVEs for a few CPEs and notify if they have an CVE-Score.

This worked like a charm in the last weeks, but since a few days i get randomly JSONDecodeErrors like this:

```
Invalid search criteria syntax: <Response [403]>
Attempted search criteria: modStartDate=2022-07-09T00:00:00:000 UTC-00:00&modEndDate=2022-07-19T00:00:00:000 UTC-00:00&cpeName=cpe:2.3:a:vmware:vcenter_server:*:*:*:*:*:*:*:*
```

Because this exception ends with an "exit()" my program stops there. Now i had exchanged the "exit()" to "raise", so i can react on this error, but this doesn't explain why i'm now getting this messages.

This happens when i'm using the following functions:

```
cve_return = nvdlib.searchCVE(cpeName=cpe,modStartDate=modStartDate,modEndDate=modEndDate)

result = nvdlib.getCVE(cve,False)
```

Btw. my changes on the get.py (Line 22-29):

old:

```
    try: # Try to convert the request to JSON. If it is not JSON, then print the response and exit.
        raw = raw.json() 
        if 'message' in raw:
            raise LookupError(raw['message'])
    except JSONDecodeError:
        print('Invalid search criteria syntax: ' + str(raw))
        print('Attempted search criteria: ' + searchCriteria)
        exit()
```

new:

```
    try: # Try to convert the request to JSON. If it is not JSON, then print the response and exit.
        raw = raw.json() 
        if 'message' in raw:
            raise LookupError(raw['message'])
    except JSONDecodeError:
        print('Invalid search criteria syntax: ' + str(raw))
        print('Attempted search criteria: ' + searchCriteria)
        raise
```

Additionally i tried the CPEs manually in a Python Shell and it worked like a charm. So it doesn't seem like an syntax problem.

Maybe anyone have an idea? At this moment is the script working, but i need a few re-runs to get every CVE.

Kind Regards
~Ithrasiel

**Comment by vehemont** [comment]
I also just pushed 0.5.8 which resolves the issue with NVDLib running exit().

**Comment by ithrasiel** [comment]
Hi,

 to your initial Question:

> NVDLib follows the 6 second delay recommendation between requests (except when using an API key). I see you've stated that you need "a few re-runs to get every CVE". Do you mean that you have to run your script multiple times to get all CVEs?

Yes, you are right. I'm starting a Loop there and retry it a few times. Normally i got an response in the first three tries.

--- 

But thanks for your suggestion with the API Key and your rework on the Library! I requested an API Key and now it works like a charm again. Now i doesn't got any retries and the programm isn't stopping anymore randomly!

Kind Regards
~Ithrasiel

**Comment by vehemont** [comment]
Regarding the need to re-run searches to get all responses, please give the new `sortPublished=True` parameter in NVDLib a try. According to the NVD API documentation, this is supposed to resolve the issue of missing CVEs when pulling a lot of them at the same time. I haven't had much luck using this parameter and have seen no difference in responses, but maybe it will resolve that issue for you.

From the NVD API guide:
> Including `sortOrder=publishedDate` changes the sort order so that the API responds with the most recently published CVE first.
When making iterative requests for a large number of CVE, such as the initial population of all CVE in a local database, sorting by the modified date may occasionally result in missing CVE. This may happen if new CVE are added during the iterative requests. Sorting by the published date avoids these errors.


Please let me know if you come across any other issues with NVDLib.
